### ISSUE TITLE
Plugin should respect the current commit

### ISSUE THREAD

**Issue by Sebmaster** [felixrieseberg/vsc-travis-ci-status#3]
I think the last build isn't very interesting - especially in projects with lots going on in different branches and the status of the specific commit git is currently on should instead be retrieved.

Problem is, it may be that a specific branch isn't enabled for building, in which case it seems reasonable to fall back to the last build status (or master?), but I'm not sure how to put that into the UI though, otherwise I'd have PRd that :confused:

**Comment by felixrieseberg** [comment]
I do agree that it would be great feature - I'm using `node-travis-ci`, so that should in theory be possible. The `response` object [here](https://github.com/felixrieseberg/vsc-travis-ci-status/blob/master/travis-status.ts#L32) has a `builds` property, which contains information about individual commit hashes.

We could do something simple - check if we can find a build for the current commit, and if so, show the hash right behind the checkmark in the statusbar. If not, fallback to the latest master build and display a master right behind the checkmark.

I'd love a PR :rainbow: Interested in doing it, by any chance?

**Comment by Sebmaster** [comment]
Definitely am interested in the functionality, but short on time at the moment. I'll see if I can wrap up some loose ends and get to it, but if you have time to implement before me I'd appreciate that as well :smile:

**Comment by gdziadkiewicz** [comment]
@Sebmaster 
Can you check it and close the issue if the new capabilities please you?

**Comment by felixrieseberg** [comment]
Actually, I think we can close this. The PR you made was :+1: and I think this is solved now.
